- src/igvfd/tests/data/inserts/award.json
- src/igvfd/tests/data/inserts/lab.json
- src/igvfd/tests/data/inserts/user.json
Added users, labs, awards from the DRAFT IGVF Metadata
User emails are not actual emails, just their first name + email domain
> IGVF-6-inserts

- src/igvfd/loadxl.py
- src/igvfd/schemas/changelogs/mixins.md
- src/igvfd/schemas/changelogs/technical_sample.md
- src/igvfd/schemas/mixins.json
- src/igvfd/schemas/technical_sample.json
- src/igvfd/tests/conftest.py
- src/igvfd/tests/data/inserts/technical_sample.json
- src/igvfd/tests/fixtures/schemas/technical_sample.py
- src/igvfd/tests/test_schema_technical_sample.py
- src/igvfd/types/sample.py
Added schema for technical sample. Added mixin for sample material.
> Igvf 69 add techical sample

- docs/updating_schemas.md
Updated schema development documentation.
> IGVF-82 Update schema development documentation

- src/igvfd/tests/data/inserts/cell_line.json
- src/igvfd/tests/data/inserts/technical_sample.json
- src/igvfd/tests/data/inserts/tissue.json
Added missing slashes in test data insert source field.
> IGVF-91-fix-missing-slashes

- src/igvfd/tests/data/inserts/user.json
Is this fine for the UUID? I just generated one and placed it in
> adding myself to the user.json test insert file

- src/igvfd/schemas/biosample.json
- src/igvfd/tests/test_schema_technical_sample.py
> Igvf 113 general polish 2

- src/igvfd/schemas/biosample.json
- src/igvfd/schemas/changelogs/biosample.md
- src/igvfd/schemas/changelogs/sample.md
- src/igvfd/schemas/changelogs/technical_sample.md
- src/igvfd/schemas/sample.json
- src/igvfd/schemas/technical_sample.json
- src/igvfd/tests/data/inserts/technical_sample.json
> IGVF-208-date-obtained-sample

- src/igvfd/schemas/changelogs/differentiated_cell.md
- src/igvfd/schemas/changelogs/differentiated_tissue.md
- src/igvfd/schemas/differentiated_cell.json
- src/igvfd/schemas/differentiated_tissue.json
- src/igvfd/tests/data/inserts/differentiated_cell.json
- src/igvfd/tests/data/inserts/differentiated_tissue.json
- src/igvfd/tests/fixtures/schemas/differentiated_cell.py
- src/igvfd/tests/fixtures/schemas/differentiated_tissue.py
- src/igvfd/tests/test_schema_differentiated_cell.py
- src/igvfd/tests/test_schema_differentiated_tissue.py
- src/igvfd/tests/test_upgrade_differentiated_cell.py
- src/igvfd/tests/test_upgrade_differentiated_tissue.py
- src/igvfd/upgrade/sample.py
This is a new branch that I have set up to handle rebase.
> IGVF-239-b Updated post-differentiation-time-unit

- src/igvfd/schemas/changelogs/tissue.md
- src/igvfd/schemas/tissue.json
- src/igvfd/tests/data/inserts/tissue.json
- src/igvfd/tests/fixtures/schemas/tissue.py
- src/igvfd/tests/test_schema_tissue.py
Added placeholder for CCF uuid.
> IGVF-332 Added placeholder for CCF uuid

- setup.cfg
- src/igvfd/__init__.py
> SNO2-15-update-boto3-botocore

- src/igvfd/loadxl.py
- src/igvfd/schemas/biomarker.json
- src/igvfd/schemas/biosample.json
- src/igvfd/schemas/changelogs/biomarker.md
- src/igvfd/tests/conftest.py
- src/igvfd/tests/data/inserts/biomarker.json
- src/igvfd/tests/data/inserts/primary_cell.json
- src/igvfd/tests/fixtures/schemas/biomarker.py
- src/igvfd/tests/fixtures/schemas/gene.py
- src/igvfd/tests/test_schema_biomarker.py
- src/igvfd/tests/test_types_biomarker.py
- src/igvfd/types/biomarker.py
> Igvf 342 biomarker

- src/igvfd/loadxl.py
- src/igvfd/schemas/changelogs/software.md
- src/igvfd/schemas/changelogs/software_version.md
- src/igvfd/schemas/software.json
- src/igvfd/schemas/software_version.json
- src/igvfd/tests/conftest.py
- src/igvfd/tests/data/inserts/software.json
- src/igvfd/tests/data/inserts/software_version.json
- src/igvfd/tests/fixtures/schemas/software.py
- src/igvfd/tests/fixtures/schemas/software_version.py
- src/igvfd/tests/test_schema_software.py
- src/igvfd/tests/test_schema_software_version.py
- src/igvfd/tests/test_types_software_version.py
- src/igvfd/types/software.py
- src/igvfd/types/software_version.py
corrected-loadxl
adding-types-files
> IGVF-331-add-software-schemas

- src/igvfd/loadxl.py
- src/igvfd/schemas/changelogs/donor.md
- src/igvfd/schemas/changelogs/human_donor.md
- src/igvfd/schemas/changelogs/rodent_donor.md
- src/igvfd/schemas/donor.json
- src/igvfd/schemas/human_donor.json
- src/igvfd/tests/conftest.py
- src/igvfd/tests/data/inserts/human_donor.json
- src/igvfd/tests/data/inserts/phenotypic_feature.json
- src/igvfd/tests/data/inserts/rodent_donor.json
- src/igvfd/tests/fixtures/schemas/human_donor.py
- src/igvfd/tests/test_schema_human_donor.py
- src/igvfd/tests/test_schema_rodent_donor.py
- src/igvfd/tests/test_upgrade_human_donor.py
- src/igvfd/upgrade/donor.py
Removed health_status_history from human donor. Added phenotypic_feature to Donor.
> Igvf 90 donor phenotypic feature

- src/igvfd/schemas/changelogs/donor.md
- src/igvfd/schemas/changelogs/human_donor.md
- src/igvfd/schemas/changelogs/rodent_donor.md
- src/igvfd/schemas/donor.json
- src/igvfd/schemas/human_donor.json
- src/igvfd/schemas/rodent_donor.json
- src/igvfd/tests/data/inserts/human_donor.json
- src/igvfd/tests/data/inserts/rodent_donor.json
- src/igvfd/tests/data/inserts/source.json
- src/igvfd/tests/fixtures/schemas/human_donor.py
- src/igvfd/tests/fixtures/schemas/rodent_donor.py
- src/igvfd/tests/test_schema_human_donor.py
- src/igvfd/tests/test_schema_rodent_donor.py
- src/igvfd/tests/test_upgrade_human_donor.py
- src/igvfd/tests/test_upgrade_rodent_donor.py
- src/igvfd/upgrade/donor.py
IGVF-386 Updated donor external resources
> IGVF-386-update-donor-external-resources

- src/igvfd/schemas/changelogs/donor.md
- src/igvfd/schemas/changelogs/human_donor.md
- src/igvfd/schemas/changelogs/rodent_donor.md
- src/igvfd/schemas/donor.json
- src/igvfd/schemas/human_donor.json
- src/igvfd/schemas/rodent_donor.json
- src/igvfd/tests/data/inserts/human_donor.json
- src/igvfd/tests/data/inserts/rodent_donor.json
- src/igvfd/tests/fixtures/schemas/human_donor.py
- src/igvfd/tests/test_schema_human_donor.py
- src/igvfd/tests/test_schema_rodent_donor.py
- src/igvfd/tests/test_upgrade_human_donor.py
- src/igvfd/upgrade/donor.py
Removed traits from donor, human donor and rodent donor. Added update code for new schema version.
> IGVF-444-remove-traits-from-donor

- src/igvfd/schemas/changelogs/biosample.md
IGVF-459 
Removed erroneous Schema version 6 entry from abstract biosample change log.
> IGVF-459 Removed Erroneous Entry From Biosample Change Log

- src/igvfd/schemas/changelogs/in_vitro_system.md
- src/igvfd/schemas/changelogs/primary_cell.md
- src/igvfd/schemas/changelogs/sample.md
- src/igvfd/schemas/changelogs/technical_sample.md
- src/igvfd/schemas/changelogs/tissue.md
- src/igvfd/schemas/changelogs/whole_organism.md
- src/igvfd/schemas/sample.json
- src/igvfd/tests/data/inserts/in_vitro_system.json
- src/igvfd/tests/data/inserts/tissue.json
- src/igvfd/tests/test_schema_in_vitro_system.py
Added sorted fraction to sample schema.
> IGVF-468-sample-sorted-fraction

- src/igvfd/searches/configs/platform_term.py
adding search columns configs to platform term
> IGVF-609-platformterm-search

- src/igvfd/audit/biosample.py
- src/igvfd/tests/test_audit_biosample.py
Added audit for biosample NIH institutional certification.
> IGVF-572 Audit for biosample NIH institutional certification.

- src/igvfd/schemas/biosample.json
- src/igvfd/schemas/in_vitro_system.json
Updated definitions for treatments and factors in schema.
> IGVF-624 Updated definitions for treatments and factors.

- src/igvfd/__init__.py
major version update due to breaking changes in the Gene object
> update version 6.0.0

- src/igvfd/__init__.py
major version change due to a breaking change of making taxa a calculated property rather than required submittable in samples
> update version to v7.0.0

- src/igvfd/schemas/changelogs/in_vitro_system.md
- src/igvfd/schemas/in_vitro_system.json
- src/igvfd/tests/data/inserts/in_vitro_system.json
- src/igvfd/tests/fixtures/schemas/in_vitro_system.py
- src/igvfd/tests/test_schema_in_vitro_system.py
- src/igvfd/tests/test_types_biosample.py
- src/igvfd/tests/test_upgrade_in_vitro_system.py
- src/igvfd/upgrade/sample.py
… time_post_factors_introduction_units
> IGVF-627-require-differentiation-properties

- src/igvfd/loadxl.py
- src/igvfd/mappings/construct_library.json
- src/igvfd/schemas/changelogs/construct_library.md
- src/igvfd/schemas/construct_library.json
- src/igvfd/tests/data/inserts/construct_library.json
update-mapping
reference-cycle-fix
> IGVF-656-add-integrated-content-files-CL

- src/igvfd/__init__.py
update major version due to the switch to the new snovault major version
> update version 9.0

- src/igvfd/__init__.py
major version change due to snovault version change
> update version 11

- src/igvfd/mappings/measurement_set.json
- src/igvfd/schemas/changelogs/measurement_set.md
- src/igvfd/schemas/measurement_set.json
- src/igvfd/tests/data/inserts/measurement_set.json
- src/igvfd/tests/test_schema_measurement_set.py
Added delivery property to the measurement set object.
> IGVF-727-add-delivery-to-measurement

- docs/updating_schemas.md
IGVF-357 updating the schema making documentation
> IGVF-357-update-schema-making-docs

- src/igvfd/audit/sample.py
- src/igvfd/mappings/in_vitro_system.json
- src/igvfd/mappings/primary_cell.json
- src/igvfd/mappings/technical_sample.json
- src/igvfd/mappings/tissue.json
- src/igvfd/mappings/whole_organism.json
- src/igvfd/tests/data/inserts/tissue.json
- src/igvfd/tests/fixtures/schemas/primary_cell.py
- src/igvfd/tests/test_audit_sample.py
Added an audit to flag non-virtual samples linked to virtual samples.
> IGVF-736-non-vitual-samples-audit

- src/igvfd/__init__.py
relaxing md5 uniqueness
removing reference and sequence data schemas
> update version 12

- src/igvfd/loadxl.py
- src/igvfd/mappings/in_vitro_system.json
- src/igvfd/mappings/multiplexed_sample.json
- src/igvfd/mappings/primary_cell.json
- src/igvfd/mappings/technical_sample.json
- src/igvfd/mappings/tissue.json
- src/igvfd/mappings/whole_organism.json
- src/igvfd/schemas/biosample.json
- src/igvfd/schemas/changelogs/multiplexed_sample.md
- src/igvfd/schemas/multiplexed_sample.json
- src/igvfd/searches/configs/multiplexed_sample.py
- src/igvfd/searches/defaults.py
- src/igvfd/tests/conftest.py
- src/igvfd/tests/data/inserts/multiplexed_sample.json
- src/igvfd/tests/fixtures/schemas/multiplexed_sample.py
- src/igvfd/tests/fixtures/schemas/phenotype_term.py
- src/igvfd/tests/test_types_sample.py
- src/igvfd/types/sample.py
> IGVF-776-add-Multiplexed-Sample

- src/igvfd/audit/construct_library.py
- src/igvfd/mappings/construct_library.json
- src/igvfd/schemas/construct_library.json
- src/igvfd/tests/test_audit_construct_library.py
> IGVF-865-relax-assoc-disease-audit

- src/igvfd/__init__.py
updating the requirement to use seqspec (move from measurments set to file)
> update version to 14.0.0

- cdk/infrastructure/config.py
> remove-old-opensearch

- src/igvfd/schemas/whole_organism.json
Fixed a typo in whole organism schema.
> IGVF-785-bugfix-whole-organism

- src/igvfd/audit/construct_library.py
- src/igvfd/mappings/analysis_set.json
- src/igvfd/mappings/auxiliary_set.json
- src/igvfd/mappings/construct_library.json
- src/igvfd/mappings/curated_set.json
- src/igvfd/mappings/measurement_set.json
- src/igvfd/mappings/model.json
- src/igvfd/mappings/prediction.json
- src/igvfd/schemas/changelogs/construct_library.md
- src/igvfd/schemas/construct_library.json
- src/igvfd/searches/configs/construct_library.py
- src/igvfd/tests/data/inserts/construct_library.json
- src/igvfd/tests/fixtures/schemas/construct_library.py
- src/igvfd/tests/test_audit_construct_library.py
- src/igvfd/tests/test_schema_construct_library.py
- src/igvfd/tests/test_upgrade_construct_library.py
- src/igvfd/upgrade/file_set.py
Renamed construct_library origins to selection_criteria.
> IGVF-860-rename-construct-library-origins

- src/igvfd/mappings/software_version.json
- src/igvfd/types/software_version.py
Embedded software id and title in software version object.
> IGVF-886-embed-prop-software-version

- src/igvfd/searches/configs/biomarker.py
Added biomarker status to config columns and facets.
> IGVF-884-add-status-biomarker-columns

- src/igvfd/__init__.py
> update version 15.0.0

- src/igvfd/mappings/modification.json
- src/igvfd/schemas/changelogs/modification.md
- src/igvfd/schemas/modification.json
- src/igvfd/tests/data/inserts/modification.json
- src/igvfd/tests/test_schema_modification.py
- src/igvfd/tests/test_types_modification.py
- src/igvfd/types/modification.py
Added ZIM3 to fused domain enums in modification.
> IGVF-916-add-zim3-to-fused-domain

- docs/updating_schemas.md
- src/igvfd/tests/testing_views.py
Fixed schema link in Updating Schema documentation.
> IGVF-814-documentation-fix-schema-link 

- src/igvfd/types/file_set.py
- src/igvfd/types/image.py
- src/igvfd/types/modification.py
- src/igvfd/types/ontology_term.py
- src/igvfd/types/phenotypic_feature.py
- src/igvfd/types/software_version.py
- src/igvfd/types/treatment.py
- src/igvfd/types/variant.py
- src/igvfd/types/workflow.py
Updated collection titles to be plural.
>  IGVF-1028-update-collections-objects-plural

- src/igvfd/mappings/analysis_set.json
- src/igvfd/mappings/auxiliary_set.json
- src/igvfd/mappings/construct_library.json
- src/igvfd/mappings/curated_set.json
- src/igvfd/mappings/measurement_set.json
- src/igvfd/mappings/model.json
- src/igvfd/mappings/prediction.json
- src/igvfd/schemas/auxiliary_set.json
- src/igvfd/schemas/changelogs/auxiliary_set.md
- src/igvfd/schemas/changelogs/model.md
- src/igvfd/schemas/changelogs/prediction.md
- src/igvfd/schemas/model.json
- src/igvfd/schemas/prediction.json
- src/igvfd/searches/configs/auxiliary_set.py
- src/igvfd/searches/configs/model.py
- src/igvfd/searches/configs/prediction.py
- src/igvfd/tests/data/inserts/auxiliary_set.json
- src/igvfd/tests/data/inserts/model.json
- src/igvfd/tests/data/inserts/prediction.json
- src/igvfd/tests/fixtures/schemas/auxiliary_set.py
- src/igvfd/tests/fixtures/schemas/model.py
- src/igvfd/tests/fixtures/schemas/prediction.py
- src/igvfd/tests/test_upgrade_auxiliary_set.py
- src/igvfd/tests/test_upgrade_model.py
- src/igvfd/tests/test_upgrade_prediction.py
- src/igvfd/types/file_set.py
- src/igvfd/upgrade/file_set.py
Changed the specific type across the various file_sets to “file_set_type”.
> IGVF-1036-update-file-sets-as-file-set-type

- src/igvfd/types/sample.py
including construct_library_sets to samples in the multiplexed_samples list of MultiplexedSample
> IGVF-1200-samples-construct-library-sets

- cdk/infrastructure/config.py
IGVF-1332-resize-indexer-worker (#720)
> merge-dev-to-main-resize-indexer-worker

- src/igvfd/searches/configs/construct_library_set.py
- src/igvfd/searches/configs/image_file.py
- src/igvfd/searches/configs/measurement_set.py
update properties in config-columns that not exist in schema
> IGVF-1099-fix-config-columns

- src/igvfd/mappings/analysis_set.json
- src/igvfd/mappings/auxiliary_set.json
- src/igvfd/mappings/construct_library_set.json
- src/igvfd/mappings/curated_set.json
- src/igvfd/mappings/in_vitro_system.json
- src/igvfd/mappings/measurement_set.json
- src/igvfd/mappings/model_set.json
- src/igvfd/mappings/multiplexed_sample.json
- src/igvfd/mappings/prediction_set.json
- src/igvfd/mappings/primary_cell.json
- src/igvfd/mappings/technical_sample.json
- src/igvfd/mappings/tissue.json
- src/igvfd/mappings/whole_organism.json
- src/igvfd/schemas/changelogs/in_vitro_system.md
- src/igvfd/schemas/in_vitro_system.json
- src/igvfd/searches/configs/in_vitro_system.py
- src/igvfd/tests/data/inserts/in_vitro_system.json
- src/igvfd/tests/data/inserts/user.json
- src/igvfd/tests/test_types_in_vitro_system.py
- src/igvfd/types/sample.py
- Add `growth_medium` to in_vitro_system
- Show on summary, columns, facets
> IGVF-1616-add-growth-media

- src/igvfd/audit/biosample.py
- src/igvfd/mappings/in_vitro_system.json
- src/igvfd/mappings/primary_cell.json
- src/igvfd/mappings/tissue.json
- src/igvfd/mappings/whole_organism.json
- src/igvfd/tests/data/inserts/user.json
- src/igvfd/tests/test_audit_biosample.py
Audit for biomarkers with same names
> IGVF-1108-audit-biomarker-name

- src/igvfd/tests/data/inserts/user.json
Added self to the new user file.
> IGVF-1816-adding-new-user
